version: '3'

services:

  postgres:
    image: postgres 
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=12345 
 
  airflow:
    build: .
    container_name: airflow
    depends_on:
      - postgres
      - clickhouse
    ports:
      - 8001:8080
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/root/airflow/plugins
      - ./airflow/dbt:/usr/local/airflow/dbt
      - ./airflow/sql-scripts:/usr/local/airflow/sql-scripts
