config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True


dbt_pet:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: clickhouse
      port: 9000
      user: default
      password: '12345'
      secure: False